version: "3.9"

services:
    #
    #
    # FRONTEND
    frontend:
        image: ${NODE_IMAGE}
        working_dir: /home/node/app
        command: yarn dev
        networks:
            - development
        volumes:
            - ../frontend:/home/node/app

    frontend-preview:
        image: ${NODE_IMAGE}
        working_dir: /home/node/app
        command: yarn preview
        ports:
            - "${PREVIEW_PORT}:80"
        networks:
            - development
        volumes:
            - ../frontend:/home/node/app

    #
    #
    # BACKEND
    backend:
        image: backend-dev
        working_dir: /home/node/app
        command: yarn dev
        networks:
            - development
        volumes:
            - ../backend:/home/node/app

    #
    #
    # TESTS
    frontend-tests-unit:
        image: unit-tests-ui
        working_dir: /home/node/app
        command: yarn test:unit:ui
        ports:
            - "${FRONTEND_UNIT_TEST_UI_PORT}:80"
        networks:
            - development
        volumes:
            - ../frontend:/home/node/app

    backend-tests-unit:
        image: unit-tests-ui
        working_dir: /home/node/app
        command: yarn test:unit:ui
        ports:
            - "${BACKEND_UNIT_TEST_UI_PORT}:80"
        networks:
            - development
        volumes:
            - ../backend:/home/node/app

    tests-e2e:
        image: ${PLAYWRIGHT_IMAGE}
        working_dir: /e2e
        depends_on:
            - frontend
            - backend
        ipc: host
        volumes:
            - ../frontend:/e2e
        command: yarn test:e2e:report
        ports:
            - "${E2E_TEST_UI_PORT}:80"

    #
    #
    # PROXY
    proxy:
        image: ${NGINX_IMAGE}
        ports:
            - "443:443"
        volumes:
            - ../_dev/tests.html:/var/www/__tests/index.html
            - ../proxy/_dev/templates:/etc/nginx/templates
            - ../_dev/keys/${LOCAL_HOST}.pem:/etc/cert/cert.pem
            - ../_dev/keys/${LOCAL_HOST}-key.pem:/etc/cert/key.pem
        depends_on:
            - frontend
            - backend
        networks:
            - development

networks:
    development:
        name: "network_development"
        driver: "bridge"
